### ISSUE TITLE
Direct endpoints for message handlers 404

### ISSUE THREAD

**Issue by joshuazmiller** [TheM4hd1/SwiftyInsta#195] opened 2020-06-10 10:17 UTC
I found these 3 endpoints returning 404s. (Did not check the other 2.)
```
/// Inbox.
case inbox = "https://i.instagram.com/api/v1/direct_v2/inbox/"
/// Recent recipients.
case recentRecipients = "https://i.instagram.com/api/v1/direct_share/recent_recipients/"
/// Ranked recipients.
case rankedRecipients = "https://i.instagram.com/api/v1/direct_v2/ranked_recipients/"
```
<img width="711" alt="Screen Shot 2020-06-10 at 3 15 20 AM" src="https://user-images.githubusercontent.com/20162542/84256501-d6ac0400-aac8-11ea-8a1b-f60fddab7dd4.png">

**Comment by vlourme** [comment] 2020-06-22 10:10
I'm getting an error too that seems linked to this issue.

```
failure(SwiftyInsta.GenericError.custom("https://i.instagram.com/api/v1/direct_v2/inbox/.\nInvalid response.\nProcessing handler returned `nil`.\n404"))
SwiftyInsta.PaginationParameters
```

This happen when I run the README example for Inbox.

**Comment by sbertix** [comment] 2020-06-22 10:26
Yep, I'm struggling to actually pinpoint the cause… it's the `404` status code that I genuinely do not understand, cause the endpoint is there.

Do you mind checking if everything works using [**Swiftagram**](https://github.com/sbertix/Swiftagram)?
Not trying to self promote (as I'm maintaining both repos), just trying to understand whether it's an "Instagram" problem (maybe some profiles not being able to access that endpoint all together), or a **SwiftyInsta** one, and I need more data points tbh.

@vlourme @joshuazmiller

**Comment by vlourme** [comment] 2020-06-22 10:48
@sbertix Do you have some example how to use Swiftagram? I tried to use it already but I didn’t understood everything (I’m pretty new to swift). If you have some example or code you’d like me to test, I’m ok!

**Comment by sbertix** [comment] 2020-06-22 11:53
Sure, please check out the Example project in the repo @vlourme

**Comment by vlourme** [comment] 2020-06-22 16:28
@sbertix I just tried to run the Followers example on the SE 2 simulator. It launch but when I login with correct credentials it crash :/

**Comment by vlourme** [comment] 2020-07-24 14:35
Any progression/news about this issue?

**Comment by sbertix** [comment] 2020-07-24 15:20
Sorry, I closed the other issue that seemed to be related to the same underlying problem and I forgot to update this. Apologies.

The body of the response returned by server is empty.\
Working with Instagram APIs, I've learnt that this is generally related to authentication issues, and **SwiftyInsta**, as of right now, as a lot of those.\
This would also explain why the same endpoints work perfectly in [**Swiftagram**](https://github.com/sbertix/Swiftagram), as it uses improved authentication flow and cookie caching.

As I said many times now, I'm only maintaining critical issues that are _fixable_ with **SwiftyInsta**'s current architecture.\
To solve this, it would literally mean rewrite it. And I've already done it. That's why we have **Swiftagram**.

I'm closing this issue.\
If you require direct messaging functionality, I would suggest considering **Swiftagram**.\
Otherwise, if somebody decides to work on authentication in the future, and thus fix this too, the can simply reopen this issue.

**Closed by sbertix** 2020-07-24 15:20 UTC
Labels: question

**Comment by TheM4hd1** [comment] 2020-08-08 21:54
just tested these endpoints, works fine for me.
can you intercept your request and share data here?
