### ISSUE TITLE
Instagram mobile website as login method

### ISSUE THREAD

**Issue by mzgnr** [TheM4hd1/SwiftyInsta#9] opened 2019-02-01 19:40 UTC
Can we use instagram mobile login web page as a login method ?

**Comment by mzgnr** [comment] 2019-02-02 09:14
I can help you with testing and developing the feature. My fork is also a Carthage compatible. We can talk about it more if you have a discord channel

**Comment by TheM4hd1** [comment] 2019-02-02 11:37
Sure, contact me by email: mahdimakhdumi@att.net

**Comment by flamme0011** [comment] 2019-04-11 13:33
Hi,
Did you find any solution or do you have any idea for this problem?

**Comment by TheM4hd1** [comment] 2019-04-11 16:53
@flamme0011  I'm working on it, but it's not stable yet.

**Comment by TheM4hd1** [comment] 2019-04-11 16:53
@flamme0011  I'm working on it, but it's not stable yet.

**Comment by freeman4706** [comment] 2019-04-15 18:49
Hello, it is great repository. Did you finish this feature ? Are you planning to publish it ?

**Comment by TheM4hd1** [comment] 2019-04-15 20:20
@freeman4706  Hello,
The feature works fine separately, but adding this feature to library requires a lot of changes.
a few functions and structures needs to be recreated.
If I release this feature it wouldn't be stable and may causes unexpected behaviors.
So fixing this issues takes time.

**Comment by mzgnr** [comment] 2019-04-15 20:36
@TheM4hd1 I would like to maintain if you publish under different branch and beta version

**Comment by TheM4hd1** [comment] 2019-04-15 21:19
@mzgnr sure, I will create a new branch when I added base structures. for now it's just a separate project. I didn't still merge codes with library.

**Comment by freeman4706** [comment] 2019-04-16 08:33
> @mzgnr sure, I will create a new branch when I added base structures. for now it's just a separate project. I didn't still merge codes with library.

Great! A new branch is good idea. When will you publish it ? Thank you.

**Comment by TheM4hd1** [comment] 2019-04-17 12:17
Thanks to @freeman4706 for implementing this feature.
It's still in beta version and may contains bug. test it and let us know if you found anything.

Usage example:

```swift
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(true)
    
    
    loginWebView = InstagramLoginWebView(frame: self.view.frame)
    self.view.addSubview(loginWebView!)
    loginWebView?.loginDelegate = self
    loginWebView?.loadInstagramLogin(isNeedPreloadForCookieSync: true)
}

extension ViewController : InstagramLoginWebViewDelegate {
    func userLoggedSuccessfully() {
        print("User Logged Successfully")
    }
    
    func webViewFinishedToLoadUser(sessionCache: SessionCache, handler: APIHandlerProtocol) {
        print("Loading user with sessioncache is successful")
    }
}
```

**Comment by flamme0011** [comment] 2019-04-19 07:56
It looks well thanks for your all effort, but after login how can we redirect our page instead of instagram main page?
And how will cache mechanism work? (I mean after first login next time user should not be login again)

**Comment by TheM4hd1** [comment] 2019-04-19 08:02
```webViewFinishedToLoadUser``` called when a user **loggedIn** successfully with a **cache**.
you can remove your ```InstagramLoginWebView``` from ```superView``` here. Save the cache in your **database**, every time a user opens the app, you should check for a cache, if cache exists, then you call ```handler.login(cache: SessionCache)```

**Comment by podycust** [comment] 2019-04-19 10:06
working great thanks. just also trying to work out how to handle the cache. save to database?

**Comment by flamme0011** [comment] 2019-04-19 10:07
Can you merge it to master please? Because it is not coming with pod update

**Comment by TheM4hd1** [comment] 2019-04-19 14:31
@podycust ```SessionCache``` supports ```Codable```, it means when you encode it, it will give you ```Data``` as output, you can save this output to your ```Local Storage``` or ```UserDefaults``` or any other databases like ```Realm```.
Also it's possible to convert ```Data``` to ```String``` by using ```String(data: data, encoding: .utf8)``` too.

@flamme0011 merged.

**Comment by podycust** [comment] 2019-04-19 17:28
Ok thanks will have to google that as codable is new to me lol

**Comment by mzgnr** [comment] 2019-04-20 19:19
@podycust just dont save it to UserDefaults for security reasons.

**Comment by podycust** [comment] 2019-04-21 09:15
@mzgnr wasn't planning on doing that! I just save the sessioncache somewhere to speed up future logins when my app starts lol

**Comment by arda0011** [comment] 2019-04-24 08:36
@TheM4hd1 Thanks for this great library.
I have a question about to store SessionCache in DB.

How can I convert SessionCache to String for storing DB and when I read from db to login system how can I convert it to SessionCache?

Thanks

**Comment by TheM4hd1** [comment] 2019-04-24 10:23
@arda0011 use `JSONDeceoder` to convert `Data` to `SessionCache` and `JSONEncoder` to convert `SessionCache` into `Data`
to convert `Data` to `String`: `String(data: data, encoding: .utf8)`
to convert `string` to `data`: `“string value”.data(using: .utf8)`

**Comment by arda0011** [comment] 2019-04-24 10:43
Thanks @TheM4hd1 you are awesome

**Comment by RealOlympusDev** [comment] 2019-04-26 05:51
@TheM4hd1 How long does it take for a session to expire?

**Comment by TheM4hd1** [comment] 2019-04-26 06:32
@RealOlympusDev 90 days as I know

**Comment by RealOlympusDev** [comment] 2019-04-26 08:24
Ok, thanks!

**Comment by freedevcoder** [comment] 2019-05-11 12:21
thanks .
do you help me for save SessionCache to file and use again after run app?

**Comment by freedevcoder** [comment] 2019-05-19 13:00
hi mehdi

do you have login in weblogin method with saved cache ?

like this code

loginWebView.loadInstagramLogin(cache: sessionCache)

**Comment by TheM4hd1** [comment] 2019-05-19 13:04
@freedevcoder 
Hi, please use [Siwa](https://github.com/TheM4hd1/Siwa) for login.
this new framework uses web api for login.

**Comment by freedevcoder** [comment] 2019-05-19 14:51
ok
but I would login to instagram in weblogin method with cookie that saved before

**Comment by TheM4hd1** [comment] 2019-05-19 15:01
no there is no method like this and it's not necessary
when you have the saved cache, you have to use handler.login(cache) method.

**Closed** 2019-05-20 16:52 UTC
Labels: Roadmap
